services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: zipzip-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - zipzip-postgres-data:/var/lib/postgresql

volumes:
  zipzip-postgres-data:
