server:
    forward-headers-strategy: framework

spring:
    config:
        import: classpath:config/application-secret.yml

    application:
        name: zipzip-server

    datasource:
        driver-class-name: org.postgresql.Driver
