server:
    forward-headers-strategy: framework
    tomcat:
        threads:
            max: 50
            min-spare: 10
        accept-count: 50

spring:
    config:
        import: classpath:config/application-secret.yml

    application:
        name: zipzip-server

    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            pool-name: zipzip-hikari
            maximum-pool-size: 20
            minimum-idle: 5
            connection-timeout: 3000
            validation-timeout: 1000
            max-lifetime: 1800000
            leak-detection-threshold: 5000
idempotency:
    auth-response-ttl: 10m
